web_site_app:
    resource: "@WebSiteAppBundle/Controller/"
    type:     annotation
    prefix:   /
    options:
        expose: true
    

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"