<?php

namespace WebSite\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RaceBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository {

}
